#!/bin/bash
if [[ $EUID -ne 0 ]];
then
exec sudo /bin/bash "$0" "$@"
fi
echo -e "#####################################"
echo -e "## Press enter to update ubuntu... ##"
echo -e "#####################################"
read dummy
echo -e "####################"
echo -e "## Updating lists ##"
echo -e "####################"
apt update
echo -e "######################"
echo -e "## Upgrading system ##"
echo -e "######################"
apt full-upgrade -y
echo -e "############################"
echo -e "## Removing unnecessaries ##"
echo -e "############################"
apt autoremove -y
echo -e "################################################"
echo -e "## Update completed, press enter to reboot... ##"
echo -e "################################################"
read dummy
reboot